import Head from 'next/head'
import Image from 'next/image'
import WeatherAPI from '../src/components/WeatherAPI'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Weather application</title>
        <meta name="description" content="Weather app, generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >

        <WeatherAPI />

      </main>

      <footer >

      </footer>
    </div>
  )
}
